
  create table "public"."deneme" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."deneme" enable row level security;

CREATE UNIQUE INDEX deneme_pkey ON public.deneme USING btree (id);

alter table "public"."deneme" add constraint "deneme_pkey" PRIMARY KEY using index "deneme_pkey";

grant delete on table "public"."deneme" to "anon";

grant insert on table "public"."deneme" to "anon";

grant references on table "public"."deneme" to "anon";

grant select on table "public"."deneme" to "anon";

grant trigger on table "public"."deneme" to "anon";

grant truncate on table "public"."deneme" to "anon";

grant update on table "public"."deneme" to "anon";

grant delete on table "public"."deneme" to "authenticated";

grant insert on table "public"."deneme" to "authenticated";

grant references on table "public"."deneme" to "authenticated";

grant select on table "public"."deneme" to "authenticated";

grant trigger on table "public"."deneme" to "authenticated";

grant truncate on table "public"."deneme" to "authenticated";

grant update on table "public"."deneme" to "authenticated";

grant delete on table "public"."deneme" to "service_role";

grant insert on table "public"."deneme" to "service_role";

grant references on table "public"."deneme" to "service_role";

grant select on table "public"."deneme" to "service_role";

grant trigger on table "public"."deneme" to "service_role";

grant truncate on table "public"."deneme" to "service_role";

grant update on table "public"."deneme" to "service_role";


